name: 'Create Dependency Branches'
description: 'Create same branch in dependency repos to spin up that service in k8s.'

inputs:
  repo:
    description: 'Repository to create branch on'
    default: ''
    required: false
  org:
    description: 'Organization or user to manage repos under'
    default: 'dmsi-io'
    required: false
  token: 
    description: 'Personal Access Token (PAT)'
    required: true
  username: 
    description: 'Username that the PAT belongs to.'
    required: true

runs:
  using: 'composite'
  steps: 

    - uses: actions/checkout@v2
      with: 
        repository: ${{ inputs.org }}/${{ inputs.repo }}
        path: ${{ inputs.repo }}
        token: ${{ inputs.token }}

    - run: |
        ls -al
        cd ${{ inputs.repo }}
        ls -al
      shell: bash