name: 'Create Dependency Branches'
description: 'Create same branch in dependency repos to spin up that service in k8s.'

inputs:
  repo:
    description: 'Repository to create branch on'
    required: true
  org:
    description: 'Organization or user to manage repos under'
    default: ${{ github.repository_owner }}
    required: false
  token:
    description: 'Personal Access Token (PAT)'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.org }}/${{ inputs.repo }}
        path: ${{ inputs.repo }}
        token: ${{ inputs.token }}

    - run: |
        echo "--- TOP LEVEL ---"
        ls -al

        cd ${{ inputs.repo }}

        echo "--- INSIDE REPO ---"
        ls -al
      shell: bash

    - run: |
        echo "--- BRANCHES ---"
        git branch -a 

        echo "--- CHECKING CURRENT BRANCH EXISTS ---"
        if git branch -a | grep ${{ github.ref_name }}; then
          echo "found match of ${{ github.ref_name }}"
        fi 

        echo "--- CHECKING CURRENT BRANCH DOES NOT EXIST ---"
        if ! git branch -a | grep ${{ github.ref_name }}; then
          echo "did not find match of ${{ github.ref_name }}" 
        fi
      shell: bash
      working-directory: ${{ inputs.repo }}
