name: 'Create Dependency Branches'
description: 'Create same branch in dependency repos to spin up that service in k8s.'

inputs:
  repos:
    description: 'Repositories to create branch on'
    default: ''
    required: false
  org:
    description: 'Organization or user to manage repos under'
    default: 'dmsi-io'
    required: false

runs:
  using: 'composite'
  steps: 
    - run: |
        echo "Using org: ${{ inputs.org }}"

        IFS=', ' read -r -a REPOS <<< "${{ inputs.repos }}"
        
        for REPO in "${REPOS[@]}"
        do
            echo "$REPO"
            echo "Cloning git@github.com:${{ inputs.org }}/$REPO.git"
            git clone git@github.com:${{ inputs.org }}/$REPO.git
            git branch -r
        done
      shell: bash