name: Test gha-create-branches

on:
  - push

jobs:
  test-gha-create-branches:
    runs-on: ubuntu-latest
    name: Test gha-create-branches on ${{ matrix.repo }}
    strategy:
      matrix:
        repo: ['k8s-ingress', 'k8s-redis', 'graphql-api']
    steps:
      - name: Create Branches
        uses: dmsi-io/gha-create-branches@main
        with:
          repo: ${{ matrix.repo }}
          token: ${{ secrets.GO_MODULES_TOKEN }}
